### ISSUE TITLE
[nad] css tables in text boxes

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-diagram#685]
### Describe the current behavior

table / tr / td tags are used to describe the text box content for the legend

example:
```html
<table>
    <tr>
        <td>
            <div class="nad-vl300to500-0 nad-legend-square"/>
        </td>
        <td>393.5 kV / -15.1°</td>
    </tr>
                <tr>
        <td>
            <div class="nad-vl300to500-1 nad-legend-square"/>
        </td>
        <td>393.0 kV / -14.7°</td>
    </tr>
</table>
```

### Describe the expected behavior

Using divs with CSS instead, something like that:
```html
<div class="table">
    <div class="row">
         <div class="nad-vl300to500-0 nad-legend-square"/>
         <div class="cell">393.5 kV / -15.1°</div>
    </div>
    <div class="row">
         <div class="nad-vl300to500-1 nad-legend-square"/>
         <div class="cell">393.0 kV / -14.7°</div>
    </div>
</div>
```
with corresponding CSS
```css
.table {
    display: table;
}
.row {
    display: table-row;
}
.cell {
    display: table-cell;
    padding: 4px;
}
```

### Describe the motivation

Less verbose SVG

**Comment by flo-dup** [comment]
It seems that the `display: table-cell` is not taking into account the padding like it did with table/tr/td, leading to a rectangle instead of a square. We could try it without the `display: table`, with simple div/span in fact:

```html
<div>
    <div><span class="nad-vl300to500-0 nad-legend-square"/>393.5 kV / -15.1°</div>
    <div><span class="nad-vl300to500-1 nad-legend-square"/>393.0 kV / -14.7°</div>
</div>
```
with corresponding CSS
```css
.nad-legend-square {
    display: inline-block;;
    width: 20px;
    height: 20px;
    background: var(--nad-vl-color, black);
    margin-right: 10px;
}
```
