### ISSUE TITLE
[sld] Highlight buses when hovering

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-diagram#708]
### Describe the current behavior

the buses can (only) be differentiated with the colors

### Describe the expected behavior

the buses can be even more differentiated with the highlight when hovering on one of the color
- in the legend
- in the diagram itself

![Image](https://github.com/user-attachments/assets/36cc1925-1040-444e-be4c-a4665ede8893)

### Describe the motivation

better interactivity, color-blind compatibility

### Extra Information

The gif example was achieved with pure CSS, but I had in mind some known limitations on this approach. Either I do recall it wrong, or the navigators have improved their support (the pseudo-selector :has is quite a new feature). The corresponding CSS was:
```css
svg:has(.sld-vl300to500-3:hover) .sld-vl300to500-3:not(.sld-breaker):not(.sld-disconnector) {stroke-width: 5px}
```
